const HaroofETahajiPictureData  =[
    {imgsrc:'../images/Haroof-e-tahaji pictures/آ.jpg',path:'/PicturesWithHaroof'},
    {imgsrc:'../images/Haroof-e-tahaji pictures/آآ.jpg',path:'/PicturesWithHaroof'},
    {imgsrc:'../images/Haroof-e-tahaji pictures/ا.jpg',path:'/PicturesWithHaroof'},
    {imgsrc:'../images/Haroof-e-tahaji pictures/اا.jpg',path:'/PicturesWithHaroof'}, 
    {imgsrc:'../images/Haroof-e-tahaji pictures/ب.jpg',path:'/PicturesWithHaroof'},
    {imgsrc:'../images/Haroof-e-tahaji pictures/بب.jpg'},
    {imgsrc:'../images/Haroof-e-tahaji pictures/پ.jpg'},
    {imgsrc:'../images/Haroof-e-tahaji pictures/پپ.jpg'}, 
    {imgsrc:'../images/Haroof-e-tahaji pictures/ت.jpg'},
    {imgsrc:'../images/Haroof-e-tahaji pictures/تت.jpg'},
    {imgsrc:'../images/Haroof-e-tahaji pictures/ث.jpg'},
    {imgsrc:'../images/Haroof-e-tahaji pictures/ثث.jpg'},
    {imgsrc:'../images/Haroof-e-tahaji pictures/ٹ.jpg'}, 
    {imgsrc:'../images/Haroof-e-tahaji pictures/ٹٹ.jpg'},
    {imgsrc:'../images/Haroof-e-tahaji pictures/ج.jpg'},
    {imgsrc:'../images/Haroof-e-tahaji pictures/جج.jpg'},
    {imgsrc:'../images/Haroof-e-tahaji pictures/چ.jpg'}, 
    {imgsrc:'../images/Haroof-e-tahaji pictures/چچ.jpg'},
    {imgsrc:'../images/Haroof-e-tahaji pictures/ح.jpg'},
    {imgsrc:'../images/Haroof-e-tahaji pictures/حح.jpg'},
    {imgsrc:'../images/Haroof-e-tahaji pictures/خ.jpg'},
    {imgsrc:'../images/Haroof-e-tahaji pictures/خخ.jpg'},
    {imgsrc:'../images/Haroof-e-tahaji pictures/د.jpg'}, 
    {imgsrc:'../images/Haroof-e-tahaji pictures/دد.jpg'},
    {imgsrc:'../images/Haroof-e-tahaji pictures/ذ.jpg'},
    {imgsrc:'../images/Haroof-e-tahaji pictures/ذذ.jpg'},
    {imgsrc:'../images/Haroof-e-tahaji pictures/ڈ.jpg'}, 
    {imgsrc:'../images/Haroof-e-tahaji pictures/ڈڈ.jpg'},
    {imgsrc:'../images/Haroof-e-tahaji pictures/ر.jpg'},
    {imgsrc:'../images/Haroof-e-tahaji pictures/رر.jpg'},
    {imgsrc:'../images/Haroof-e-tahaji pictures/ز.jpg'},
    {imgsrc:'../images/Haroof-e-tahaji pictures/زژ.jpg'}, 
    {imgsrc:'../images/Haroof-e-tahaji pictures/ڑ.jpg'},
    {imgsrc:'../images/Haroof-e-tahaji pictures/ڑڑ.jpg'},
    {imgsrc:'../images/Haroof-e-tahaji pictures/س.jpg'},
    {imgsrc:'../images/Haroof-e-tahaji pictures/سس.jpg'}, 
    {imgsrc:'../images/Haroof-e-tahaji pictures/ش.jpg'},
    {imgsrc:'../images/Haroof-e-tahaji pictures/شش.jpg'},
    {imgsrc:'../images/Haroof-e-tahaji pictures/ص.jpg'},
    {imgsrc:'../images/Haroof-e-tahaji pictures/صص.jpg'},
    {imgsrc:'../images/Haroof-e-tahaji pictures/ض.jpg'}, 
    {imgsrc:'../images/Haroof-e-tahaji pictures/ضض.jpg'},
    {imgsrc:'../images/Haroof-e-tahaji pictures/ط.jpg'},
    {imgsrc:'../images/Haroof-e-tahaji pictures/طط.jpg'},
    {imgsrc:'../images/Haroof-e-tahaji pictures/ظ.jpg'}, 
    {imgsrc:'../images/Haroof-e-tahaji pictures/ظظ.jpg'},
    {imgsrc:'../images/Haroof-e-tahaji pictures/ع.jpg'},
    {imgsrc:'../images/Haroof-e-tahaji pictures/عع.jpg'},
    {imgsrc:'../images/Haroof-e-tahaji pictures/غ.jpg'},
    {imgsrc:'../images/Haroof-e-tahaji pictures/غغ.jpg'},
    {imgsrc:'../images/Haroof-e-tahaji pictures/ف.jpg'}, 
    {imgsrc:'../images/Haroof-e-tahaji pictures/فف.jpg'},
    {imgsrc:'../images/Haroof-e-tahaji pictures/ق.jpg'},
    {imgsrc:'../images/Haroof-e-tahaji pictures/قق.jpg'},
    {imgsrc:'../images/Haroof-e-tahaji pictures/ک.jpg'}, 
    {imgsrc:'../images/Haroof-e-tahaji pictures/کک.jpg'},
    {imgsrc:'../images/Haroof-e-tahaji pictures/گ.jpg'},
    {imgsrc:'../images/Haroof-e-tahaji pictures/گگ.jpg'},
    {imgsrc:'../images/Haroof-e-tahaji pictures/ل.jpg'},
    {imgsrc:'../images/Haroof-e-tahaji pictures/لل.jpg'}, 
    {imgsrc:'../images/Haroof-e-tahaji pictures/م.jpg'},
    {imgsrc:'../images/Haroof-e-tahaji pictures/مم.jpg'},
    {imgsrc:'../images/Haroof-e-tahaji pictures/ن.jpg'},
    {imgsrc:'../images/Haroof-e-tahaji pictures/نن.jpg'}, 
    {imgsrc:'../images/Haroof-e-tahaji pictures/ہ.jpg'},
    {imgsrc:'../images/Haroof-e-tahaji pictures/ہہ.jpg'},
    {imgsrc:'../images/Haroof-e-tahaji pictures/و.jpg'},
    {imgsrc:'../images/Haroof-e-tahaji pictures/وو.jpg'},
    {imgsrc:'../images/Haroof-e-tahaji pictures/ی.jpg'}, 
    {imgsrc:'../images/Haroof-e-tahaji pictures/یی.jpg'},
    
    

]

export default HaroofETahajiPictureData 